name: Example Python Application Workflow

on:
  push:
    branches:
      - main  # or any other branch you want to trigger the workflow

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Specifies the runner

    steps:
    - uses: actions/checkout@v3
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Installs dependencies from a requirements.txt file, if you have one

    - name: Run a Python script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        # Here we're passing the API keys to the environment of this step
      run: |
        python script_using_keys.py
        # This is your script that uses the API keys. Replace script_using_keys.py
        # with the path to your actual script
