name: Example Workflow with Serper
on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script with Serper API
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}  # Use the secret
      run: |
        echo "Using the Serper and OpenAI API keys"
        # Replace the following line with your command that uses the API keys.
        # For example, calling a script: python use_apis.py
